"""
Compiler Agent - DSL to hping3 using LangChain
"""

from langchain.prompts import PromptTemplate
from langchain.output_parsers import StrOutputParser


COMPILER_PROMPT = PromptTemplate(
    template="""You are a Network Test Compiler. Convert DSL to hping3 bash script.

DSL Schema:
{dsl_json}

RULES for hping3:
- TCP mode (default): hping3 [flags] target
- UDP mode: hping3 -2 target
- ICMP mode: hping3 -1 target
- SYN flag: -S, ACK: -A, FIN: -F, RST: -R, PSH: -P, URG: -U
- Rate: --flood (max), --fast (10pps), --faster, or -i uX (microseconds)
- Count: -c N
- Source port: -s PORT (or random if not specified)
- Dest port: -p PORT
- TTL: -t N
- Spoof: -a IP
- Random source: --rand-source
- Fragmentation: -f, --mtu N

Generate a complete bash script:
```bash
#!/bin/bash
# Generated by AI Test Agent

TARGET="{target}"
# ... build command ...

hping3 [all flags] $TARGET
```

Include ALL relevant flags based on DSL.
If stealth=true, use --rand-source and low rate.
If scan=true, use appropriate flags.
If stress=true, use --flood or high rate.

OUTPUT: Return ONLY the complete bash script, nothing else.
""",
    input_variables=["dsl_json", "target"]
)


class CompilerAgent:
    def __init__(self, llm):
        self.llm = llm
        self.chain = COMPILER_PROMPT | self.llm | StrOutputParser()

    def compile(self, dsl: dict) -> tuple[str, list[str]]:
        """Compile DSL to hping3 script"""
        conflicts = []

        if dsl.get("ip", {}).get("random_source") and dsl.get("ip", {}).get("spoof"):
            conflicts.append("Warning: Both random_source and spoof specified")

        if dsl.get("intent", {}).get("stealth") and dsl.get("traffic", {}).get("rate") == "flood":
            conflicts.append("Warning: Stealth mode with flood rate conflicts")

        if dsl.get("traceroute") and dsl.get("ip", {}).get("random_source"):
            conflicts.append("Warning: Random source may break traceroute replies")

        script = self.chain.invoke({
            "dsl_json": str(dsl),
            "target": dsl.get("target", "")
        })

        return script, conflicts
