"""
Compiler Agent - DSL to hping3 using Minimax
"""

import re


COMPILER_PROMPT = """You are a Network Test Compiler. Convert DSL to hping3 bash script.

DSL Schema:
{dsl_json}

RULES for hping3:
- TCP mode (default): hping3 [flags] target
- UDP mode: hping3 -2 target
- ICMP mode: hping3 -1 target
- SYN flag: -S, ACK: -A, FIN: -F, RST: -R, PSH: -P, URG: -U
- Rate: --flood (max), --fast (10pps), --faster, or -i uX (microseconds)
- Count: -c N
- Source port: -s PORT (or random if not specified)
- Dest port: -p PORT
- TTL: -t N
- Spoof: -a IP
- Random source: --rand-source
- Fragmentation: -f, --mtu N

Generate a complete bash script:
```bash
#!/bin/bash
# Generated by AI Test Agent

TARGET="{target}"
# ... build command ...

hping3 [all flags] $TARGET
```

Include ALL relevant flags based on DSL.
If stealth=true, use --rand-source and low rate.
If scan=true, use appropriate flags.
If stress=true, use --flood or high rate.

OUTPUT: Return ONLY the complete bash script, nothing else.
"""


class CompilerAgent:
    def __init__(self, llm):
        self.llm = llm

    def compile(self, dsl: dict) -> tuple[str, list[str]]:
        """Compile DSL to hping3 script"""
        conflicts = []

        if dsl.get("ip", {}).get("random_source") and dsl.get("ip", {}).get("spoof"):
            conflicts.append("Warning: Both random_source and spoof specified")

        if dsl.get("intent", {}).get("stealth") and dsl.get("traffic", {}).get("rate") == "flood":
            conflicts.append("Warning: Stealth mode with flood rate conflicts")

        if dsl.get("traceroute") and dsl.get("ip", {}).get("random_source"):
            conflicts.append("Warning: Random source may break traceroute replies")

        prompt = COMPILER_PROMPT.format(
            dsl_json=str(dsl),
            target=dsl.get("target", "")
        )

        script = self.llm([{"role": "user", "content": prompt}])

        # Clean up the response - extract script from markdown if present
        script = self._extract_script(script)

        return script, conflicts

    def _extract_script(self, text: str) -> str:
        """Extract bash script from response"""
        # Try to find bash code block
        match = re.search(r'```(?:bash)?\s*([\s\S]*?)```', text)
        if match:
            return match.group(1).strip()

        # Try to find script content
        if text.startswith("#!/bin/bash") or text.startswith("hping3"):
            return text.strip()

        # Return as-is if no markdown formatting
        return text.strip()
